AttSchool/urls.py
from AttSchool import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("appMain.urls")),
    path("", include("appV.urls")),
    path("", include("appE.urls")),
    path("", include("appT.urls")),
    path("", include("appO.urls")),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path("register/", user_views.UserCreateView.as_view(), name="register"),
    path("profile/", user_views.ProfileView.as_view(), name="profile"),
    path("profile/update", user_views.UpdateProfileView.as_view(), name="upprofile"),
    path("logout/", user_views.logout_user.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appE/urls.py
from django.urls import path
from . import views

app_name = "appE"

urlpatterns = [
    path("ehome/", views.eHomeview.as_view(), name="ehome"),
]

appMain/urls.py
from django.urls import path
from . import views

app_name = "appMain"

urlpatterns = [
    path("", views.Homeview.as_view(), name="home"),
    path("ghome/", views.gHomeview.as_view(), name="ghome"),
    path("aboutus/", views.Aboutusview.as_view(), name="aboutus"),
]

appO/urls.py
from django.urls import path
from . import views

app_name = "appO"

urlpatterns = [
    # Home views
    path("ohome/", views.oHomeview.as_view(), name="ohome"),
    # Teacher views
    path("Teacher/list/", views.o_listTeacher.as_view(), name="o_listTeacher"),
    # CRUD Teacher views
    path("Teacher/add/", views.AddTeacher.as_view(), name="AddTeacher"),
    path(
        "Teacher/<slug:slug>",
        views.o_view_teacher.as_view(),
        name="o_teacherdetail",
    ),
    path(
        "Teacher/<slug:slug>/update/",
        views.UpTeacher.as_view(),
        name="UpdateTeacher",
    ),
    path(
        "Teacher/<slug:slug>/delete/",
        views.DelTeacher.as_view(),
        name="DeleteTeacher",
    ),
    # Classe views
    path(
        "Classes/list/",
        views.o_listClasses.as_view(),
        name="o_listClasses",
    ),
    path("Classes/<int:pk>", views.dashClass.as_view(), name="dashClass"),
    # CRUD Classe views
    path("Classes/add/", views.AddClasses.as_view(), name="AddClasses"),
    path(
        "Classes/<slug:slug>/update/", views.UpClasses.as_view(), name="UpdateClasses"
    ),
    path(
        "Classes/<slug:slug>/delete/", views.DelClasses.as_view(), name="DeleteClasses"
    ),
    # Student views
    path("<int:pk>/Student/list/", views.o_listStudent.as_view(), name="o_listStudent"),
    # CRUD Student views
    path("Student/add/", views.AddStudentes.as_view(), name="AddStudentes"),
    path("Student/<slug:slug>", views.o_view_student.as_view(), name="o_studentdetail"),
    path(
        "Student/<slug:slug>/update/",
        views.UpStudentes.as_view(),
        name="UpdateStudentes",
    ),
    path(
        "Student/<slug:slug>/delete/",
        views.DelStudentes.as_view(),
        name="DeleteStudentes",
    ),
    # Attendance views
    path(
        "ohome/listClasses/<str:klasname>/o_attendence/",
        views.o_Att.as_view(),
        name="o_attendence",
    ),
    path(
        "ohome/listClasses/<str:klasname>/<str:skooY>/<int:pk>/o_attmgt/",
        views.o_AttMgt.as_view(),
        name="o_attmgt",
    ),
    path(
        "ohome/listClasses/<int:class_id>/confirm",
        views.confirm.as_view(),
        name="confirm",
    ),
]

templates/NjSidenav.html
<ul class="nj-side-list">
    <li class="nj-side-item">
        <a href="{% url 'appMain:home' %}">
            <span class="menu-icon">
                <i class="fa fa-light fa-school"></i>
            </span>
            <span class="menu-title">Home</span>
        </a>
    </li>
    {% if user.is_authenticated %}
    {% if user.is_student %}
    <li class="nj-side-item">
        <a href="#student">
            <span class="menu-icon">
                <i class="fa fa-light fa-list"></i>
            </span>
            <span class="menu-title">Classes</span>
        </a>
    </li>
    {% elif user.is_teacher %}
    <li class="nj-side-item">
        <a href="#teacher">
            <span class="menu-icon">
                <i class="fa fa-light fa-list"></i>
            </span>
            <span class="menu-title">Classes</span>
        </a>
    </li>
    {% elif user.is_overseer %}
    <li class="nj-side-item">
        <a href="{% url 'appO:o_listTeacher' %}">
            <span class="menu-icon">
                <i class="fa fa-light fa-list"></i>
            </span>
            <span class="menu-title">List Teacher</span>
        </a>
    </li>
    <li class="nj-side-item">
        <a href="{% url 'appO:o_listClasses' %}">
            <span class="menu-icon">
                <i class="fa fa-light fa-list"></i>
            </span>
            <span class="menu-title">Classes</span>
        </a>
    </li>
    {% else %}
    <li class="nj-side-item">
        <a class="disabled" href="#">
            <span class="menu-icon">
                <i class="fa fa-light fa-list"></i>
            </span>
            <span class="menu-title">Classes</span>
        </a>
    </li>
    {% endif %}
    {% endif %}
    <li class="nj-side-item">
        <a href="{% url 'appMain:aboutus'%}">
            <span class="menu-icon">
                <i class="fa fa-regular fa-circle-info"></i>
            </span>
            <span class="menu-title">About Us</span>
        </a>
    </li>
    <div class="nj-side-list-footer">
        <span>
            {% if user.is_authenticated %}
            <li class="nj-side-item">
                <div onclick="myFunction(this)">
                    <a href="#">
                        <img src="{{ user.profile.image.url }}" class="menu-icon user_avatar">
                        <span class="menu-title">{{ user.get_username }}</span>
                    </a>
                </div>
                <div class="nj-sub-side-list" id="nj-sub-side-list">
                    <ul>
                        <li class="menu-item">
                            <a href="{% url 'profile'%}">
                                <span class="menu-icon">
                                    <i class="fa fa-light fa-user-tag"></i>
                                </span>
                                <span class="menu-title">Profil</span>
                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="{% url 'logout' %}">
                                <span class="menu-icon">
                                    <i class="fa fa-regular fa-arrow-right-from-bracket"></i>
                                </span>
                                <span class="menu-title">Logout</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            {% else %}
            <li class="nj-side-item">
                <a class="nav-link" href="{% url 'login'%}?next={{request.path}}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-arrow-right-to-bracket"></i>
                    </span>
                    <span class="menu-title">Login</span>
                </a>
            </li>
            <li class="nj-side-item">
                <a href="{% url 'register'%}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-user-plus"></i>
                    </span>
                    <span class="menu-title">Sign Up</span>
                </a>
            </li>
            {% endif %}
        </span>
    </div>
</ul>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Nj Mcl">

    <!-- Webpage Title -->
    {% if page_title %}
    <title>{{ page_title }} | School Management System</title>
    {% else %}
    <title>School Management System</title>
    {% endif %}
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <!-- Font-Awesome CSS -->
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.min.css'%}">

    <link rel="stylesheet" href="{% static 'nj/css/NjStyle.css'%}">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
</head>

<body>
    <header class="nj-header" id="nj-header">
        <div class="nj-logo-wrapper">
            <a href="{% url 'appMain:home' %}" class="nj-logo"><img src="{% static 'img/mytitle.png' %}" alt="Logo"></a>
        </div>
        {% if user.is_authenticated %}
        {% if user.is_overseer %}
        <form action="">
            <input name="search" type="text" class="form-control mr-sm-2" id="" placeholder="name, matricul,..">
            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">
                <i class="fa fa-search"></i>
            </button>
        </form>
        {% else %}
        <ul class="nj-header-list">
            {% if user.is_authenticated %}
            <li class="nj-header-list-item">
                <a href="{% url 'profile'%}">
                    <span class="menu-icon">
                        <i class="fa fa-light fa-user-tag"></i>
                    </span>
                    <span class="menu-title">Profil</span>
                </a>
            </li>
            <li class="nj-header-list-item">
                <a href="{% url 'logout' %}">
                    <span class="menu-icon">
                        <i class="fa fa-regular fa-arrow-right-from-bracket"></i>
                    </span>
                    <span class="menu-title">Logout</span>
                </a>
            </li>
            {% else %}
            <li class="nj-header-list-item nj-header-list-item-btn">
                <a href="{% url 'login'%}?next={{request.path}}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-arrow-right-to-bracket"></i>
                    </span>
                    <span class="menu-title">Login</span>
                </a>
            </li>

            <li class="nj-header-list-item nj-header-list-item-btn">
                <a href="{% url 'register'%}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-user-plus"></i>
                    </span>
                    <span class="menu-title">Sign Up</span>
                </a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
        {% endif %}
        <div id="nj-header-trigger" class="nj-header-trigger" onclick="toggleSidebar(this)">
            <span></span>
        </div>
    </header>
    <aside class="nj-sidebar has-bg-image" id="nj-sidebar">
        <div class="image-wrapper">
            <img src="{% static 'img/forest.jpg' %}" alt="sidebar background" />
        </div>
        {% include 'NjSidenav.html' %}
    </aside>
    <main class="nj-main-content">
        {% include 'messages.html' %}
        <div class="nj-content">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer class="nj-footer">
        <small>
            © 2022 made with
            <span>&#10084;</span> by -
            <a target="_blank" href="#"> Anjara </a>
        </small>
    </footer>
    <script type="text/javascript" src="{% static 'nj/js/NjMain.js'%}"></script>
    <!-- Jquery -->
    <script language="JavaScript" type="text/javascript" src="{% static 'jquery/js/jquery.min.js'%}"></script>
</body>

</html>

templates/baselog.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Nj Mcl">
    <!-- Webpage Title -->
    {% if page_title %}
    <title>{{ page_title }} | School Management System</title>
    {% else %}
    <title>School Management System</title>
    {% endif %}
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <!-- Font-Awesome CSS -->
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.min.css'%}">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    <link rel="stylesheet" href="{% static 'nj/css/NjStyle.css'%}">
    <link rel="stylesheet" href="{% static 'users/css/Njlog.css'%}">
    {% block headContent %}
    {% endblock headContent %}
</head>

<body>
    <header class="nj-header" id="nj-header">
        <div class="nj-logo-wrapper">
            <a href="{% url 'appMain:home' %}" class="nj-logo"><img src="{% static 'img/mytitle.png' %}" alt="Logo"></a>
        </div>
        <ul class="nj-header-list">
            {% if user.is_authenticated %}
            <li class="nj-header-list-item">
                <a href="{% url 'profile'%}">
                    <span class="menu-icon">
                        <i class="fa fa-light fa-user-tag"></i>
                    </span>
                    <span class="menu-title">Profil</span>
                </a>
            </li>
            <li class="nj-header-list-item">
                <a href="{% url 'logout' %}">
                    <span class="menu-icon">
                        <i class="fa fa-regular fa-arrow-right-from-bracket"></i>
                    </span>
                    <span class="menu-title">Logout</span>
                </a>
            </li>
            {% else %}
            <li class="nj-header-list-item nj-header-list-item-btn">
                <a href="{% url 'login'%}?next={{request.path}}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-arrow-right-to-bracket"></i>
                    </span>
                    <span class="menu-title">Login</span>
                </a>
            </li>

            <li class="nj-header-list-item nj-header-list-item-btn">
                <a href="{% url 'register'%}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-user-plus"></i>
                    </span>
                    <span class="menu-title">Sign Up</span>
                </a>
            </li>
            {% endif %}
        </ul>
        <div id="nj-header-trigger" class="nj-header-trigger" onclick="toggleSidebar(this)">
            <span></span>
        </div>
    </header>
    <main class="nj-main-content">
        {% include 'messages.html' %}
        <div class="nj-content">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer class="nj-footer">
        <small>
            © 2022 made with
            <span>&#10084;</span> by -
            <a target="_blank" href="#"> Anjara </a>
        </small>
    </footer>
    <script type="text/javascript" src="{% static 'nj/js/NjMain.js'%}"></script>
    <script language="JavaScript" type="text/javascript"
        src="{% static 'bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <!-- Jquery -->
    <script language="JavaScript" type="text/javascript" src="{% static 'jquery/js/jquery.min.js'%}"></script>
</body>

</html>

templates/logbase.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Nj Mcl">
    <!-- Webpage Title -->
    {% if page_title %}
    <title>{{ page_title }} | School Management System</title>
    {% else %}
    <title>School Management System</title>
    {% endif %}
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <!-- Font-Awesome CSS -->
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.min.css'%}">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    <link rel="stylesheet" href="{% static 'my/css/NjStyle.css'%}">
    {% block headContent %}
    {% endblock headContent %}
</head>

<body>
    <header class="nj-header" id="nj-header">
        <div class="nj-logo-wrapper">
            <a href="{% url 'appMain:home' %}" class="nj-logo"><img src="{% static 'img/mytitle.png' %}" alt="Logo"></a>
        </div>
        <ul class="nj-header-list">
            {% if user.is_authenticated %}
            <li class="nj-header-list-item">
                <a href="{% url 'profile'%}">
                    <span class="menu-icon">
                        <i class="fa fa-light fa-user-tag"></i>
                    </span>
                    <span class="menu-title">Profil</span>
                </a>
            </li>
            <li class="nj-header-list-item">
                <a href="{% url 'logout' %}">
                    <span class="menu-icon">
                        <i class="fa fa-regular fa-arrow-right-from-bracket"></i>
                    </span>
                    <span class="menu-title">Logout</span>
                </a>
            </li>
            {% else %}
            <li class="nj-header-list-item nj-header-list-item-btn">
                <a href="{% url 'login'%}?next={{request.path}}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-arrow-right-to-bracket"></i>
                    </span>
                    <span class="menu-title">Login</span>
                </a>
            </li>

            <li class="nj-header-list-item nj-header-list-item-btn">
                <a href="{% url 'register'%}">
                    <span class="menu-icon">
                        <i class="fa fa-thin fa-user-plus"></i>
                    </span>
                    <span class="menu-title">Sign Up</span>
                </a>
            </li>
            {% endif %}
        </ul>
        <div id="nj-header-trigger" class="nj-header-trigger" onclick="toggleSidebar(this)">
            <span></span>
        </div>
    </header>
    <main class="nj-main-content">
        {% include 'messages.html' %}
        <div class="nj-content">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer class="nj-footer">
        <small>
            © 2022 made with
            <span>&#10084;</span> by -
            <a target="_blank" href="#"> Anjara </a>
        </small>
    </footer>
    <script type="text/javascript" src="{% static 'my/js/NjMain.js'%}"></script>
    <script language="JavaScript" type="text/javascript"
        src="{% static 'bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <!-- Jquery -->
    <script language="JavaScript" type="text/javascript" src="{% static 'jquery/js/jquery.min.js'%}"></script>
</body>

</html>

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}