AttSchool/urls.py
from AttSchool import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("appMain.urls")),
    path("", include("appV.urls")),
    path("", include("appE.urls")),
    path("", include("appT.urls")),
    path("", include("appO.urls")),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path("register/", user_views.UserCreateView.as_view(), name="register"),
    path("profile/", user_views.ProfileView.as_view(), name="profile"),
    path("profile/update", user_views.UpdateProfileView.as_view(), name="upprofile"),
    path("logout/", user_views.logout_user.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appE/urls.py
from django.urls import path
from . import views

app_name = "appE"

urlpatterns = [
    path("ehome/", views.eHomeview.as_view(), name="ehome"),
]

appO/urls.py
from django.urls import path
from . import views

app_name = "appO"

urlpatterns = [
    # Home views
    path("ohome/", views.oHomeview.as_view(), name="ohome"),
    # Teacher views
    path("Teacher/list/", views.o_listTeacher.as_view(), name="o_listTeacher"),
    # CRUD Teacher views
    path("Teacher/add/", views.AddTeacher.as_view(), name="AddTeacher"),
    path(
        "Teacher/<slug:slug>",
        views.o_view_teacher.as_view(),
        name="o_teacherdetail",
    ),
    path(
        "Teacher/<slug:slug>/update/",
        views.UpTeacher.as_view(),
        name="UpdateTeacher",
    ),
    path(
        "Teacher/<slug:slug>/delete/",
        views.DelTeacher.as_view(),
        name="DeleteTeacher",
    ),
    # Classe views
    path(
        "Classes/list/",
        views.o_listClasses.as_view(),
        name="o_listClasses",
    ),
    path("Classes/<int:pk>", views.dashClass.as_view(), name="dashClass"),
    # CRUD Classe views
    path("Classes/add/", views.AddClasses.as_view(), name="AddClasses"),
    path(
        "Classes/<slug:slug>/update/", views.UpClasses.as_view(), name="UpdateClasses"
    ),
    path(
        "Classes/<slug:slug>/delete/", views.DelClasses.as_view(), name="DeleteClasses"
    ),
    # Student views
    path("<int:pk>/Student/list/", views.o_listStudent.as_view(), name="o_listStudent"),
    # CRUD Student views
    path("Student/add/", views.AddStudentes.as_view(), name="AddStudentes"),
    path("Student/<slug:slug>", views.o_view_student.as_view(), name="o_studentdetail"),
    path(
        "Student/<slug:slug>/update/",
        views.UpStudentes.as_view(),
        name="UpdateStudentes",
    ),
    path(
        "Student/<slug:slug>/delete/",
        views.DelStudentes.as_view(),
        name="DeleteStudentes",
    ),
    # Attendance views
    path(
        "ohome/listClasses/<str:klasname>/o_attendence/",
        views.o_Att.as_view(),
        name="o_attendence",
    ),
    path(
        "ohome/listClasses/<str:klasname>/<str:skooY>/<int:pk>/o_attmgt/",
        views.o_AttMgt.as_view(),
        name="o_attmgt",
    ),
    path(
        "ohome/listClasses/<int:class_id>/confirm",
        views.confirm.as_view(),
        name="confirm",
    ),
]

appO/forms.py
from django import forms
from appMain.models import Eleve, Classe, Teacher


class addTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            "nom",
            "prenom",
            "dob",
            "pob",
            "gender",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["nom"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Nom")}
        )
        self.fields["prenom"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Prénom")}
        )
        self.fields["dob"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Date of birth")}
        )
        self.fields["pob"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Place of birth")}
        )
        self.fields["gender"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Gender")}
        )


class addStudentForm(forms.ModelForm):
    class Meta:
        model = Eleve
        fields = [
            "student_code",
            "nom",
            "prenom",
            "dob",
            "pob",
            "gender",
            "class_id",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student_code"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Student code")}
        )
        self.fields["nom"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Nom")}
        )
        self.fields["prenom"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Prénom")}
        )
        self.fields["dob"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Date of birth")}
        )
        self.fields["pob"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Place of birth")}
        )
        self.fields["gender"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Gender")}
        )
        self.fields["class_id"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Classe")}
        )


class updateStudentForm(forms.ModelForm):
    class Meta:
        model = Eleve
        fields = [
            "student_code",
            "nom",
            "prenom",
            "dob",
            "pob",
            "gender",
            "class_id",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student_code"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Student code")}
        )
        self.fields["nom"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Nom")}
        )
        self.fields["prenom"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Prénom")}
        )
        self.fields["dob"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Date of birth")}
        )
        self.fields["pob"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Place of birth")}
        )
        self.fields["gender"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Gender")}
        )
        self.fields["class_id"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Classe")}
        )


class addClasseForm(forms.ModelForm):
    class Meta:
        model = Classe
        fields = ["Classe_name", "school_year", "teacher_responsable"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["Classe_name"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Classe Name")}
        )
        self.fields["school_year"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("School Year")}
        )
        self.fields["teacher_responsable"].widget.attrs.update(
            {"class": ("form-control"), "placeholder": ("Responsable")}
        )

appO/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from appMain.models import Teacher, Classe, Eleve, Presence
from .forms import addStudentForm, updateStudentForm, addClasseForm, addTeacherForm
from django.utils.text import slugify
import json
from django.contrib import messages

User = get_user_model()


class RedirectToPreviousMixin:

    default_redirect = "/"

    def get(self, request, *args, **kwargs):
        request.session["previous_page"] = request.META.get(
            "HTTP_REFERER", self.default_redirect
        )
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return self.request.session["previous_page"]


# Create teacher
class AddTeacher(LoginRequiredMixin, generic.TemplateView):
    form_class = addTeacherForm
    template_name = "appO/CRUD/teacher/addTeacher.html"
    page_title = "Add Teacher"

    def get(self, request, *args, **kwargs):
        context = {"form": self.form_class(), "page_title": self.page_title}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        name = request.POST.get("nom")
        name1 = request.POST.get("prenom")
        username = f"{name}_{name1}"
        if form.is_valid:
            user = User.objects.create_user(
                username=username,
                email="{}@example.com".format(username),
                password=request.POST.get("dob"),
                is_visitor=False,
                is_teacher=True,
            )
            f = form.save(commit=False)
            f.t_user = user
            f.slug = slugify(request.POST.get("nom") + "-" + request.POST.get("prenom"))
            f.save()
            return redirect("appO:o_listTeacher")


# Retrive teacher
class o_listTeacher(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/CRUD/teacher/o_listTeacher.html"

    def get(self, request, *args, **kwargs):
        listTeacher = Teacher.objects.all()
        context = {"listTeacher": listTeacher, "page_title": "List Teacher"}
        return render(request, self.template_name, context)


class o_view_teacher(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/CRUD/teacher/o_teacher_details.html"

    def get(self, request, *args, **kwargs):
        slug = self.kwargs["slug"]
        teacher = get_object_or_404(Teacher, slug=slug)
        return render(request, self.template_name, {"teacher": teacher})


# Update teacher
class UpTeacher(LoginRequiredMixin, RedirectToPreviousMixin, UpdateView):
    model = Teacher
    template_name = "appO/CRUD/teacher/upTeacher.html"
    form_class = addTeacherForm
    extra_context = {"page_title": "Update Teacher"}


# Delete teacher
class DelTeacher(LoginRequiredMixin, RedirectToPreviousMixin, DeleteView):
    model = Teacher
    template_name = "appO/CRUD/delObj.html"
    extra_context = {"page_title": "Delete Teacher"}


# Create classes
class AddClasses(LoginRequiredMixin, generic.TemplateView):
    form_class = addClasseForm
    template_name = "appO/CRUD/classe/addClasses.html"

    def get(self, request, *args, **kwargs):
        context = {"form": self.form_class(), "page_title": "Add Classe"}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid:
            f = form.save(commit=False)
            f.slug = slugify(
                request.POST.get("Classe_name") + "-" + request.POST.get("school_year")
            )
            f.save()
            return redirect("appO:o_listClasses")


# Retrive teacher
class o_listClasses(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/CRUD/classe/o_listclass.html"
    extra_context = {"page_title": "Class List"}

    def get(self, request, *args, **kwargs):
        listClass = Classe.objects.all().order_by("Classe_name")
        context = {"listClass": listClass}
        return render(request, self.template_name, context)


class dashClass(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/CRUD/classe/dashboard_class.html"
    page_title = "Dashboard Classe"

    def get_context_data(self, **kwargs):
        context = super(dashClass, self).get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        context["classes"] = Classe.objects.filter(pk=pk)
        context["numblistStuds"] = Eleve.objects.filter(class_id=pk).count()
        context["listStuds"] = Eleve.objects.filter(class_id=pk)
        context["page_title"] = self.page_title
        return context


# Update std
class UpClasses(LoginRequiredMixin, RedirectToPreviousMixin, UpdateView):
    model = Classe
    template_name = "appO/CRUD/classe/upClasse.html"
    form_class = addClasseForm
    extra_context = {"page_title": "Update Classe"}


# Delete classe
class DelClasses(LoginRequiredMixin, RedirectToPreviousMixin, DeleteView):
    model = Classe
    template_name = "appO/CRUD/delObj.html"
    extra_context = {"page_title": "Delete Classe"}


# Create std
class AddStudentes(LoginRequiredMixin, generic.TemplateView):
    form_class = addStudentForm
    template_name = "appO/CRUD/std/addStud.html"

    def get(self, request, *args, **kwargs):
        context = {"form": self.form_class(), "page_title": "Add Studente"}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        name = request.POST.get("nom")
        name1 = request.POST.get("prenom")
        username = f"{name}_{name1}"
        if form.is_valid:
            user = User.objects.create_user(
                username=username,
                email="{}@example.com".format(username),
                password=request.POST.get("dob"),
                is_visitor=False,
                is_student=True,
            )
            f = form.save(commit=False)
            f.user = user
            f.slug = slugify(request.POST.get("nom") + "-" + request.POST.get("prenom"))
            f.class_id = Classe.objects.filter(pk=request.POST.get("class_id")).first()
            f.save()
            return redirect("appO:o_listClasses")


# Retrive std
class o_listStudent(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/CRUD/std/o_listStud.html"
    page_title = "Student List"

    def get_context_data(self, **kwargs):
        context = super(o_listStudent, self).get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        context["listStuds"] = Eleve.objects.filter(class_id=pk)
        context["classes"] = Classe.objects.filter(pk=pk)
        context["page_title"] = self.page_title
        return context


class o_view_student(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/CRUD/std/o_student_details.html"

    def get(self, request, *args, **kwargs):
        slug = self.kwargs["slug"]
        student = get_object_or_404(Eleve, slug=slug)
        return render(request, self.template_name, {"student": student})


# Update std
class UpStudentes(LoginRequiredMixin, RedirectToPreviousMixin, UpdateView):
    model = Eleve
    template_name = "appO/CRUD/std/upStud.html"
    form_class = updateStudentForm
    extra_context = {"page_title": "Update Student"}


# Delete std
class DelStudentes(LoginRequiredMixin, RedirectToPreviousMixin, DeleteView):
    model = Eleve
    template_name = "appO/CRUD/delObj.html"
    extra_context = {"page_title": "Delete Student"}


class o_Att(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/o_att.html"

    def get(self, request, *args, **kwargs):
        klasname = self.kwargs["klasname"]
        listPresence = Presence.objects.all().order_by("attendance_date")
        context = {
            "listPresence": listPresence,
            "klasname": klasname,
            "page_title": "Test",
        }
        return render(request, self.template_name, context)


class o_Att_by_date(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/o_att.html"
    page_title = "Test o_Att_by_date"

    def get_context_data(self, **kwargs):
        context = super(o_Att_by_date, self).get_context_data(**kwargs)
        att_date = self.kwargs["att_date"]
        context["listPresence"] = Presence.objects.filter(attendance_date=att_date)
        context["klasname"] = self.kwargs["klasname"]
        context["page_title"] = self.page_title
        return context


class o_AttMgt(LoginRequiredMixin, generic.TemplateView):
    template_name = "appO/o_attmgt.html"
    page_title = "Student List"

    def get_context_data(self, **kwargs):
        context = super(o_AttMgt, self).get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        context["listStuds"] = Eleve.objects.filter(class_id=pk)
        context["klasname"] = self.kwargs["klasname"]
        context["skooY"] = self.kwargs["skooY"]
        context["class_id"] = pk
        context["page_title"] = self.page_title
        return context


class confirm(LoginRequiredMixin, generic.TemplateView):
    def post(self, request, *args, **kwargs):
        class_id = self.kwargs["class_id"]
        listStuds = Eleve.objects.filter(class_id=class_id)
        for student in listStuds:
            status = request.POST[student.student_code]
            if status != "present":
                statu = "False"
            statu = "True"
            date_ = request.POST["mydate"]
            a = Presence(student=student, attendance_date=date_, status=statu)
            a.save()
        return HttpResponse("Ok")


# OHome views here.

appO/templates/appO/CRUD/teacher/addTeacher.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card card-default rounded-0 shadow ">
        <div class="card-header">
            <div class="d-flex w-100 align-items-center justify-content-between">
                <h4 class="card-title fw-bold">Add Teacher</h4>
                <div class="tools">
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container-fluid">
                <form method="POST">
                    {% csrf_token %}
                    <div class="mdc-layout-grid">
                        <div class="mdc-layout-grid__inner">
                            {% for field in form %}
                            <div class="form-group mb-3">
                                {{ field }}
                            </div>
                            {% endfor %}
                            <button class="w-100 btn btn-ghost sign-up" type="submit">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
Modal

appO/templates/appO/CRUD/teacher/o_listTeacher.html
{% extends 'base.html' %}

{% block content %}
<style>
    .noundline {
        text-decoration: none;
    }

    .not-visible {
        display: none;
    }

    h1 {
        color: white;
    }

</style>
<div class="text-center">
    <div class="spinner-border text-primary" role="status" id="spinner"></div>
</div>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card card-default rounded-0 shadow ">
        <div class="card-header">
            <div class="d-flex w-100 align-items-center justify-content-between">
                <h4 class="card-title fw-bold">Teacher List</h4>
                <div class="tools">
                    <a class="btn btn-info rounded-0 bg-gradient btn-sm" href="{% url 'appO:AddTeacher' %}"
                        title="Add Class"><i class="fa fa-solid fa-plus"></i> Add Teacher
                    </a>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container-fluid">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr class="bg-danger bg-opacity-0 text-light">
                            <th scope="col" class="px-2 py-2 text-center">Nom et Prénoms</th>
                            <th scope="col" class="px-2 py-2 text-center">Gender</th>
                            <th scope="col" class="text-center"></th>
                        </tr>
                    </thead>
                    <tbody id="table-body-box">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="module">
    const spinner = document.getElementById('spinner')
    const tableBody = document.getElementById('table-body-box')
    if ('{{listTeacher}}') {
        setTimeout(() => {
            spinner.classList.add('not-visible')
            tableBody.innerHTML += `
                {% for teacher in listTeacher %}
                    <tr>
                        <td class="text-center">{{ teacher.nom }} {{ teacher.prenom }}</td>
                        <td class="text-center">{{ teacher.gender }}</td>
                        <td class="text-center">
                            <a class="btn btn-outline-info btn-sm view-data" href="{{ teacher.get_absolute_url }}">
                            <i class="fa fa-eye"></i>
                            </a>
                            <a class="btn btn-outline-primary btn-sm edit-data" title="Edit" href="{% url 'appO:UpdateTeacher' teacher.slug %}">
                                <i class="fa fa-edit"></i>
                                </a>
                            <a class="btn btn-outline-danger btn-sm delete-data" title="Delete" href="{% url 'appO:DeleteTeacher' teacher.slug %}">
                                    <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                `
        }, 500)
    } else {
        setTimeout(() => {
            spinner.classList.add('not-visible')
            tableBody.innerHTML += `
                <p>Failed to load data</p>
                `
        }, 500)
    }
</script>
{% endblock %}

appO/templates/appO/CRUD/teacher/o_teacher_details.html
{% extends 'base.html' %}

{% block content %}
<style>
    .noundline {
        text-decoration: none;
    }

    .not-visible {
        display: none;
    }

</style>
<div class="text-center">
    <div class="spinner-border" role="status" id="spinner"></div>
</div>


<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card card-default rounded-0 shadow ">
        <div class="card-header">
            <div class="d-flex w-100 align-items-center justify-content-between">
                <div class="tools">
                    <a class="btn btn-outline-info" onclick="history.back()" title="Go to Teacher List"><i
                            class="fa fa-regular fa-arrow-left"></i></a>
                </div>
                <h4 class="card-title fw-bold" id="catp"></h4>
            </div>
        </div>
        <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12" id="body-box">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="module">
    const spinner = document.getElementById('spinner')
    const tableBody = document.getElementById('body-box')

    if ('{{teacher}}') {
        setTimeout(() => {
            spinner.classList.add('not-visible')
            tableBody.innerHTML += `
                        <dl>
                            <dt class="text-muted">Fullname:</dt>
                            <dd class="ps-3">{{ teacher.nom }} {{ teacher.prenom }}</dd>
                            <dt class="text-muted">Gender:</dt>
                            <dd class="ps-3">{{ teacher.gender }}</dd>
                            <dt class="text-muted">Birthday:</dt>
                            <dd class="ps-3">{{ teacher.dob|date:"d F Y" }} à {{ teacher.pob }}</dd>
                        </dl>
                `
        }, 500)
    } else {
        setTimeout(() => {
            spinner.classList.add('not-visible')
            tableBody.innerHTML += `
                <p>Failed to load data</p>
                `
        }, 500)
    }
</script>
{% endblock %}

appO/templates/appO/CRUD/teacher/upTeacher.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card card-default rounded-0 shadow ">
        <div class="card-header">
            <div class="d-flex w-100 align-items-center justify-content-between">
                <h4 class="card-title fw-bold">Update Teacher</h4>
                <div class="tools">
                </div>
            </div>
        </div>
        <div class="card-body">
            <form method="POST">
                <div class="container-fluid">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group mb-3 ">
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button class="w-100 btn btn-outline-primary" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}